# ####################################################################################################### #
# Copyright (c) 2024 Oracle and/or its affiliates,  All rights reserved.                                  #
# Licensed under the Universal Permissive License v 1.0 as shown at https: //oss.oracle.com/licenses/upl. #
# Author: Cosmin Tudor                                                                                    #
# Author email: cosmin.tudor@oracle.com                                                                   #
# Last Modified: Fri Jan 05 2024                                                                          #
# Modified by: Cosmin Tudor, email: cosmin.tudor@oracle.com                                               #
# ####################################################################################################### #

---
vaults_configuration:
  eu-frankfurt-1:
    default_compartment_id: GDAD-POC-CERT-VAULT-KEYS-KEY
    keys:
      GDAD-POC-CA-KEY-PHX-KEY:
        algorithm: RSA
        length: 512
        name: gdad_poc_ca_key
        protection_mode: HSM
        vault_key: GDAD-POC-VAULT-KEY
      GDAD-POC-TDE-KEY-ORASPACE-KEY:
        algorithm: AES
        name: gdad_poc_TDE_key-oraspace
        protection_mode: SOFTWARE
        vault_key: GDAD-POC-VAULT-KEY
    vaults:
      GDAD-POC-VAULT-KEY:
        name: gdad_poc_vault
  us-ashburn-1:
    default_compartment_id: GDAD-POC-CERT-VAULT-KEYS-KEY
    keys:
      GDAD-POC-CA-KEY-PHX-KEY:
        algorithm: RSA
        length: 512
        name: gdad_poc_ca_key
        protection_mode: HSM
        vault_key: GDAD-POC-VAULT-KEY
      GDAD-POC-TDE-KEY-ORASPACE-KEY:
        algorithm: AES
        name: gdad_poc_TDE_key-oraspace
        protection_mode: SOFTWARE
        vault_key: GDAD-POC-VAULT-KEY
    vaults:
      GDAD-POC-VAULT-KEY:
        name: gdad_poc_vault